[theme]
primaryColor = "#0078AC"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E5FFFE"
textColor = "#005275"
font = "sans serif"

[server]
fileWatcherType = "none"
headless = true
port = 8502
enableCORS = false

[client]
toolbarMode="viewer"
showUserMenu = false

[global]
developmentMode = false